# Generated by Django 2.0.6 on 2018-07-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20180706_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_data',
            name='release_date',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
